export const ErrorCodes = {
  // Generic — produced by the backend's error classifier
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INVALID_ID: "INVALID_ID",
  INVALID_JSON: "INVALID_JSON",
  PAYLOAD_TOO_LARGE: "PAYLOAD_TOO_LARGE",
  DUPLICATE_RESOURCE: "DUPLICATE_RESOURCE",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  INVALID_TOKEN: "INVALID_TOKEN",
  TOO_MANY_REQUESTS: "TOO_MANY_REQUESTS",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",

  // Auth
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",
  ACCOUNT_DISABLED: "ACCOUNT_DISABLED",
  PASSWORD_CHANGE_REQUIRED: "PASSWORD_CHANGE_REQUIRED",
  FORBIDDEN: "FORBIDDEN",
  EMAIL_ALREADY_REGISTERED: "EMAIL_ALREADY_REGISTERED",
  INVALID_OR_EXPIRED_CODE: "INVALID_OR_EXPIRED_CODE",
  TOO_MANY_ATTEMPTS: "TOO_MANY_ATTEMPTS",

  // Customers
  ONBOARDING_REQUIRED: "ONBOARDING_REQUIRED",
  ACCOUNT_BLOCKED: "ACCOUNT_BLOCKED",
  ONBOARDING_ALREADY_COMPLETED: "ONBOARDING_ALREADY_COMPLETED",
  ACCOUNT_HAS_OPEN_ORDERS: "ACCOUNT_HAS_OPEN_ORDERS",
  ADDRESS_LIMIT_REACHED: "ADDRESS_LIMIT_REACHED",

  // Stores
  STORE_CLOSED: "STORE_CLOSED",
  STORE_NOT_ACCEPTING_ORDERS: "STORE_NOT_ACCEPTING_ORDERS",
  OUTSIDE_DELIVERY_AREA: "OUTSIDE_DELIVERY_AREA",

  // Uploads
  INVALID_UPLOAD: "INVALID_UPLOAD",
  UPLOAD_LIMIT_REACHED: "UPLOAD_LIMIT_REACHED",

  // Orders
  TOO_MANY_OPEN_ORDERS: "TOO_MANY_OPEN_ORDERS",
  INVALID_ORDER_TRANSITION: "INVALID_ORDER_TRANSITION",
  ORDER_STATUS_CHANGED: "ORDER_STATUS_CHANGED",
  BILL_CHANGED: "BILL_CHANGED",
  BILL_EXPIRED: "BILL_EXPIRED",
  REORDER_NOT_ALLOWED: "REORDER_NOT_ALLOWED",

  // Not found
  ORDER_NOT_FOUND: "ORDER_NOT_FOUND",
  STORE_NOT_FOUND: "STORE_NOT_FOUND",
  ADDRESS_NOT_FOUND: "ADDRESS_NOT_FOUND",
  CUSTOMER_NOT_FOUND: "CUSTOMER_NOT_FOUND",
  ROUTE_NOT_FOUND: "ROUTE_NOT_FOUND",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
